### ISSUE TITLE
Content and curation policy for the Zenodo-communities (D2.2, Sep)

### ISSUE THREAD

**Issue by lnielsen** [zenodo/horizon-zen#21]
```[tasklist]
### Tasks
- [ ] https://github.com/zenodo/horizon-zen/issues/35
- [ ] Review EOSC HE requirements
- [ ] Create a QA process for HE requirements
- [ ] Automatically add Open Research Europe platform publications to EOR-community
```
