### ISSUE TITLE
Prefill EOR-community with existing records

### ISSUE THREAD

**Issue by lnielsen** [zenodo/horizon-zen#35]
```[tasklist]
### Tasks
- [ ] Create dataset of records matching curation policy
- [ ] Automation: it should be possible to continueosly scout for records to include
- [ ] Automatically add Open Research Europe platform publications to EOR-community
- [ ] Quality assurance process for prefilling
```
