### ISSUE TITLE
Configure and test support for authentication with EU-Login

### ISSUE THREAD

**Issue by lnielsen** [zenodo/horizon-zen#37]
```[tasklist]
### Tasks
- [ ] Obtain credentials for EU Login from EC
- [ ] Obtain documentation from the EC on integrating EU Login
- [ ] Design login page with the new login option
- [ ] Configure EU Login on QA system
- [ ] Deploy EU Login to production system
```
