### ISSUE TITLE
Public training session (MS9, Apr 23)

### ISSUE THREAD

**Issue by lnielsen** [zenodo/horizon-zen#42]
```[tasklist]
### Tasks
- [ ] Brainstorm: content, announcement channels, tools/services
- [ ] Annoucement of webinar
- [ ] Prepare content/slides
```
